# Generated by Django 4.2.19 on 2025-02-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmaticpart2', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicemodel',
            name='number',
            field=models.CharField(default='UNKNOWN', max_length=50),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='concept',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='provider',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='state',
            field=models.CharField(max_length=50),
        ),
    ]
